name: Update Role
method: PUT
url: ${API_HOST}/roles/$role_id
body:
  content: |-
    {
      "description": "Updated description"
    }
  content_type: application/json
auth:
  type: bearer_token
  bearer_token:
    token: $bearer_token
headers:
- name: content-type
  value: application/json
